export const employees = [
  {
    id: "1",
    name: "Aarav Sharma",
    email: "aarav.sharma@company.com",
    department: "Engineering",
    role: "Senior Engineer",
    status: "Active",
    joiningDate: "2021-03-15",
    image: "",
  },
  {
    id: "2",
    name: "Priya Nair",
    email: "priya.nair@company.com",
    department: "Design",
    role: "UI/UX Designer",
    status: "Active",
    joiningDate: "2022-07-01",
    image: "",
  },
  {
    id: "3",
    name: "Rohan Mehta",
    email: "rohan.mehta@company.com",
    department: "Marketing",
    role: "Marketing Executive",
    status: "On Leave",
    joiningDate: "2020-11-20",
    image: "",
  },
  {
    id: "4",
    name: "Sneha Kapoor",
    email: "sneha.kapoor@company.com",
    department: "Human Resources",
    role: "HR Manager",
    status: "Active",
    joiningDate: "2019-05-10",
    image: "",
  },
  {
    id: "5",
    name: "Vikram Singh",
    email: "vikram.singh@company.com",
    department: "Sales",
    role: "Sales Representative",
    status: "Active",
    joiningDate: "2023-01-12",
    image: "",
  },
  {
    id: "6",
    name: "Ananya Reddy",
    email: "ananya.reddy@company.com",
    department: "Engineering",
    role: "Software Engineer",
    status: "On Leave",
    joiningDate: "2022-09-05",
    image: "",
  },
  {
    id: "7",
    name: "Karan Malhotra",
    email: "karan.malhotra@company.com",
    department: "Finance",
    role: "Accountant",
    status: "Active",
    joiningDate: "2021-08-30",
    image: "",
  },
  {
    id: "8",
    name: "Ishita Joshi",
    email: "ishita.joshi@company.com",
    department: "Design",
    role: "UI/UX Designer",
    status: "Inactive",
    joiningDate: "2020-02-18",
    image: "",
  },
  {
    id: "9",
    name: "Aditya Kumar",
    email: "aditya.kumar@company.com",
    department: "Engineering",
    role: "Software Engineer",
    status: "Active",
    joiningDate: "2023-06-22",
    image: "",
  },
  {
    id: "10",
    name: "Meera Iyer",
    email: "meera.iyer@company.com",
    department: "Product",
    role: "Product Manager",
    status: "Active",
    joiningDate: "2021-12-01",
    image: "",
  },
  {
    id: "11",
    name: "Rahul Verma",
    email: "rahul.verma@company.com",
    department: "Sales",
    role: "Sales Representative",
    status: "On Leave",
    joiningDate: "2022-04-14",
    image: "",
  },
  {
    id: "12",
    name: "Divya Menon",
    email: "divya.menon@company.com",
    department: "Marketing",
    role: "Marketing Executive",
    status: "Active",
    joiningDate: "2020-10-08",
    image: "",
  },
  {
    id: "13",
    name: "Sanjay Gupta",
    email: "sanjay.gupta@company.com",
    department: "Finance",
    role: "Accountant",
    status: "Active",
    joiningDate: "2019-09-25",
    image: "",
  },
  {
    id: "14",
    name: "Pooja Bhatt",
    email: "pooja.bhatt@company.com",
    department: "Human Resources",
    role: "HR Manager",
    status: "Inactive",
    joiningDate: "2021-01-30",
    image: "",
  },
  {
    id: "15",
    name: "Nikhil Rao",
    email: "nikhil.rao@company.com",
    department: "Engineering",
    role: "Senior Engineer",
    status: "Active",
    joiningDate: "2020-06-17",
    image: "",
  },
];